export const SIGN_IN = {
  SUCCESS: 'SIGN_IN_SUCCESS',
  FAILURE: 'SIGN_IN_FAILURE'
}

export const SIGN_UP = {
  SUCCESS: 'SIGN_UP_SUCCESS',
  FAILURE: 'SIGN_UP_FAILURE'
}

export const AUTH_MODAL_TOGGLE = {
  SIGN_IN: 'TOGGLE_SIGN_IN_MODAL',
  SIGN_UP: 'TOGGLE_SIGN_UP_MODAL'
}

export const GAME = {
  NEW: 'GET_NEW_GAME',
  UPDATE_BOARD: 'UPDATE_BOARD',
  PLAY_LETTER: 'PLAY_LETTER',
  UNPLAY_LETTER: 'UNPLAY_LETTER',
  PLAYER_JOINED: 'PLAYER_JOINED'
}

export const LETTER_IN_PLAY = {
  SELECTED: 'LETTER_SELECTED',
  UNSELECTED: 'LETTER_UNSELECTED'
}

export const GAMES = {
  GET_GAMES: 'GET_GAMES'
}
